// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vravggohdyyjbdcvegor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZyYXZnZ29oZHl5amJkY3ZlZ29yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjQyODkwMjIsImV4cCI6MjAzOTg2NTAyMn0.hvSo0QqGQAB31fqIb4P-G-TDon35PsMYM_nBzE1DmlY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);